### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by nma** [ieee8023/shortscience.org#12]
I noticed that the site does not support HTTPS, I have done the setup for other sites using LetsEncrypt which is a free HTTPS cert provider.

If we know the hosting provider, we can work out a way to get the green checkmark so Firefox doesn't complain about insecure logins.

**Comment by ieee8023** [comment]
Yes we don't have SSL setup. There are many issues when maintaining a service running SSL, the initial setup configuration, maintaining a working configuration while upgrading the server, and certificate renewal management. We currently do not want to risk a misconfiguration which would prevent all users from accessing the site.

We have limited resources and all effort goes into having the most impact on user experience and having the most impact on research. We currently do not see man the middle (MITM) attacks in coffee shops or government/corporate spying (which would be prevented with SSL) to be a major concern for the impact of the site.

**Comment by nma** [comment]
Yes, I understand the the limited resources, and also the fact that MITM / spying mitigation would be a mild issue at best considering the information on the site are public / will be public. 

Mainly my point is that depending on your hosting provider, AWS with ACM, or Heroku with Automated LetsEncrypt, HTTPS would be a trivial add. Then certain browsers will stop complaining about it. Firefox is especially noisy at it.

After glancing more at the Dockerfiles, the site seems to be self hosted on Docker. So in light of that, attempting to add HTTPS now would definitely add more problems then it would solve.
