### ISSUE TITLE
How do you submit a summary?

### ISSUE THREAD

**Issue by jaypatravali** [ieee8023/shortscience.org#3]

**Comment by ieee8023** [comment]
If you log in you can see a link in the top right menu that says "add summary" there you search for a paper and then write a summary in the box at the bottom. Searching by the entire title is best or using the doi or arxiv id. 

Does that work for you?

**Comment by jaypatravali** [comment]
Oh okay, I get it. The paper  I was searching was a recent IEEE robotics conference paper which is yet to appear in the their  database. So it was all intuitive until the point where I had no search result, where for me no results meant I am in the wrong place to add. 

Thanks anyways!
