### ISSUE TITLE
formatting is flying when try to print a page to PDF

### ISSUE THREAD

**Issue by IvanKush** [ieee8023/shortscience.org#5]
Chromium 58.0.3029.110.
Is it possible to redesign for possibility of printing to PDF.

for example:
http://www.shortscience.org/paper?bibtexKey=journals/corr/1611.00712

![mad_jang_2017](https://user-images.githubusercontent.com/11693432/27519355-7fb09610-59fa-11e7-9b01-e55aeed9b3ff.png)

[maddison2017_jang2017_ss.pdf](https://github.com/ieee8023/shortscience.org/files/1100581/maddison2017_jang2017_ss.pdf)

**Comment by ieee8023** [comment]
Yes, we can add a css style to specify how the page can look when printed. Thanks for reporting this. I expect we can have it done within a week.

**Comment by ieee8023** [comment]
This should be all set! Please let us know if it is not working correctly on any page.
